sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123698745
  redis:
    host: localhost
    port: 6379
    password: 123698745
    database: 0
oss:
  qiniu:
    domain: "cdn.emotionalbug.top"
    accessKey: "89VRcOeJLPI3HAuf_lbdT0qU6KrazC7_KdtCZsxT"
    secretKey: "UBMz3-03Cw-z-qkIfbMqbvFygbP_72nZCCodlSkg"
    bucketName: "hjbsport"