sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123698745
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid:  wx99f358f8ac559ba6
    secret: 549368899d57b1ead8aa5b2dd3fca263
oss:
  qiniu:
    domain: "cdn.emotionalbug.top"
    accessKey: "89VRcOeJLPI3HAuf_lbdT0qU6KrazC7_KdtCZsxT"
    secretKey: "UBMz3-03Cw-z-qkIfbMqbvFygbP_72nZCCodlSkg"
    bucketName: "hjbsport"